### ISSUE TITLE
Running for agents which disappear at target

### ISSUE THREAD

**Issue by furkancanturk** [Jiaoyang-Li/CBSH2#8]
How can we run/change the code for the MAPF problem which agents "disappear at target"?

**Comment by Jiaoyang-Li** [comment]
The current code does not support this. If you want the agents to disappear at target, you need to modify the conflict detection functions and the constraint and reservation tables. I have made this change to a similar codebase EECBS ( which is a bounded suboptimal version of this code), you can take a look at these two commits: 
https://github.com/Jiaoyang-Li/EECBS/commit/3c49216a4f8802b5c1b5f31e49bf0c21829b2301
https://github.com/Jiaoyang-Li/EECBS/commit/f92b5ef654f2fc6f390364100b58ff06af1a542e
The changes to this code should be very similar.

**Comment by furkancanturk** [comment]
Thank you! I'll try to adapt the code like those commits.
